<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>9a91673e-ab21-42e3-9009-964c8230ddba</uuid>
	<name>Points</name>
	<type>19</type>
	<res_file_key>f10cfea0-0c98-4d71-ac7f-5dfd24fd5983</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>90de9d53-87ea-43e8-beb9-add74112f31d</uuid>
			<name>Face&lt;1&gt;</name>
			<type>5</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>4cfc688b-a72c-445e-aa16-55ab25f482fb</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0.027362189650334809</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>-1</item>
			</normal>
			<vector>
				<item>0</item>
				<item>1</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-9.969436344496943e-05</min>
			<max>0.099794057808413883</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<point/>
	<points_def_mode>0</points_def_mode>
	<purpose>0</purpose>
	<points_table_def_mode>0</points_table_def_mode>
	<points_analytic_def_mode>0</points_analytic_def_mode>
	<points_analytic_def_line>
		<p1>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p1>
		<p2>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p2>
	</points_analytic_def_line>
	<points_analytic_def_rect>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<normal>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</normal>
		<up>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</up>
		<width>0</width>
		<height>0</height>
	</points_analytic_def_rect>
	<points_analytic_def_sphere>
		<center>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</center>
		<radius>0</radius>
	</points_analytic_def_sphere>
	<points_count>100</points_count>
	<points_spacing>0.0040000000000000001</points_spacing>
	<use_mesh_based_point_generation>false</use_mesh_based_point_generation>
	<file_path/>
	<file_time>0</file_time>
	<media>false</media>
</feature>
