<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>443382b1-6ea6-41ec-a9f2-59a036117fac</uuid>
	<name>Cut Plot 1 Geometry</name>
	<type>14</type>
	<res_file_key>e0c4ef67-9464-4fd9-9a5c-c86ab1c3a5da</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>false</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>3c181664-5ef8-40f8-89f8-89e87201546a</uuid>
			<name>Right Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>4cfc688b-a72c-445e-aa16-55ab25f482fb</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>-0.02248499207214965</item>
			</origin>
			<normal>
				<item>1</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>-0</item>
				<item>-0</item>
				<item>-1</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-0.024426473417377078</min>
			<max>0.024426473417377078</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<medias>
		<item>1</item>
	</medias>
</feature>
